### ISSUE TITLE
Evolution de la synchronisation MTD

### ISSUE THREAD

**Issue by jacquesfize** [PnX-SI/mtd_sync#1]
## TODO LIST

- [ ] Ajouter des tests unitaires
- [ ] Vérification du bon fonctionnement avec la 2.15 (Geonature Branch : Develop)
- [ ] Ajout dans Docker ? **Question plus générale :** Comment installer un module externe sur un GeoNature sur Docker
- [ ] Refactoriser + Optimiser
   - [ ] Insertion/Mise à jour groupé 
   - [ ] Reprendre la méthode `associate_actors()`
- [ ] Test d'intégration ? 
- [ ] Publication sur PyPi ? Création d'une CI

# TODOLIST PART 2 

- [ ] Gérer le cas ou aucun UUID d'organisme n'est récupéré
    - [ ] si nom organisme
        - [ ]  créer un organisme et récupérer son UUID
        - [ ] sinon
        - [ ]  Si un utilisateur dans la BDD possède le même mail que l'acteur
            -  [ ]  associe cette acteur au CA/JDD
        - [ ]  Sinon
            - [ ]  Si acteur de type "contact principal"
                - [ ]  Créer un utilisateur "vide" (pas de nom, ni d'email) avec un UUID
                - [ ]  Sinon
                    - [ ]  On essaie l'association avec l'acteur suivant (si il y en existe), sinon on passe aux métadonnées suivantes.

- [ ] Tester si `id_af` existe en base dans la fonction `sync_af_and_ds_by_user`
- [ ] dans `sync_af`, si aucun UUID n'est retournée par MTD: 
   - [ ] on passe la synchro ? 
   - [ ] on crée un AF ?  (à décider !)
- [ ] Si un acteur n’apparaît plus dans le retour de l'API MTD, on le supprime également dans la base de données ?

**Comment by christophe-ramet** [comment]
N'est plus d'actualité
